#!/bin/bash

NOTEDIR=~/Documents/nNotes
VERSION=0.0.0

if [ -z "$*" ]; then 
    vim $NOTEDIR/$(date +%F-%A).nn
else
    while test $# -gt 0; do
        case "$1" in
            -h|--help)
                echo "nNotes version $VERSION"
                echo "-t | --todo - display all unresolved todo items"
                echo "-d | --date - display specific date"
                exit 0
                ;;
            -t|--todo)
                # gather all unresolved todo:es in a doc called todo.nn
                #grep -h o ~/Documents/notes/* | egrep "^o" > todo.nn
                egrep -n ^o[[:space:]] $NOTEDIR/* > todo_files.list
                awk -F  ":" '{print $3}' todo_files.list > todo.nn
                # open document
                vim todo.nn
                while read f1 <&3 && read f2 <&4; do
                    linenumber=$(echo $f1 | awk -F ":" '{print $2}')
                    read_to_file=$(echo $f1 | awk -F ":" '{print $1}')
                    sed -i "${linenumber}s/.*/$f2/" "$read_to_file"
                done 3<todo_files.list 4<todo.nn
                exit 0
                ;;
            -d|--date)
                wished_date=$(ls $NOTEDIR/$2*)
                if [ -z $wished_date ]; then
                    echo "Not available"
                else
                    vim $wished_date
                fi
                exit 0
                ;;
            *)
                break
                ;;
        esac
    done
fi
